name: Build KSU Kernel

on:
  workflow_dispatch:
    branches:
      - 'sixteen'

jobs:
  build_lavender_ksu:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        target: [SM-G9980]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip \
            zstd \
            bison flex bc libelf-dev libssl-dev

      - name: Cache Clang toolchain
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: ./clang
          key: clang-r547379-${{ github.run_id }}

      - name: Fetch Clang Toolchain
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/yanzihan/clang-r547379 --depth=1 clang

      - name: Fetch prebuilt mkbootimg from yanzihan repo
        run: |
          rm -rf ./mkbootimg
          git clone --depth=1 https://github.com/yanzihan/mkbootimg.git ./mkbootimg
          chmod +x ./mkbootimg/mkbootimg ./mkbootimg/unpackbootimg
          echo "${{ github.workspace }}/mkbootimg" >> $GITHUB_PATH

      - name: Fetch AnyKernel3
        run: |
          git clone https://github.com/yanzihan/AnyKernel3 -b samsung ./AnyKernel3

      - name: Build KSU Kernel
        run: |
          chmod +x ./build_sm8350.sh
          ./build_sm8350.sh ${{ matrix.target }} --ksu
          cp ./AnyKernel3/Lavender* ./

      - name: Release KSU Kernel
        uses: softprops/action-gh-release@v2
        with:
          files: |
            boot.img
            dtbo.img
            Lavender*.zip
          name: KSU‑Kernel‑${{ github.run_id }}
          tag_name: ksu‑${{ github.run_id }}
          body: |
            Kernel:5.4.304 | Clang:clang‑r547379
            ✅ KernelSU Enabled build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
